--
-- init.sql: create tables and triggers used for testing.
--
--

\set ON_ERROR_STOP 1

begin;

set role postgres;

-- statement-level trigger source table
create table fast_a (
  id int generated always as identity
);

comment on table fast_a is
  'Source table for statement-level insert trigger test.';
comment on column fast_a.id is
  'Primary key column (generated by postgres).';

-- statement-level trigger destination table
create table fast_b (
  id int
);

comment on table fast_b is
  'Destination table for statement-level insert trigger test.';
comment on column fast_b.id is
  'Primary key column from source table';

-- statement-level insert trigger function
create function on_fast_a_insert() returns trigger as $$
declare
  r record;
begin
  insert into fast_b select * from new_rows;
  return NULL;
end$$ language 'plpgsql';

comment on function on_fast_a_insert() is
  'statement-level insert trigger function';

create trigger on_fast_a_insert after insert on fast_a
  referencing new table as new_rows
  for each statement execute function on_fast_a_insert();

comment on trigger on_fast_a_insert on fast_a is
  'statement-level insert trigger';

-- row-level trigger source table
create table slow_a (
  id int generated always as identity
);

comment on table slow_a is
  'Source table for row-level insert trigger test.';
comment on column slow_a.id is
  'Primary key column (generated by postgres).';

-- row-level trigger destination table
create table slow_b (
  id int
);

comment on table slow_b is
  'Destination table for row-level insert trigger test.';
comment on column slow_b.id is
  'Primary key column from source table';

-- row-level insert trigger function
create function on_slow_a_insert() returns trigger as $$
begin
  insert into slow_b values (NEW.id);
  return NULL;
end$$ language 'plpgsql';

comment on function on_slow_a_insert() is
  'row-level insert trigger function';

-- row-level insert trigger
create trigger on_slow_a_insert after insert on slow_a
  for each row execute function on_slow_a_insert();

comment on trigger on_slow_a_insert on slow_a is
  'row-level insert trigger';

commit;
